remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
title: Sentify
description: Sebuah aplikasi website yang memanfaatkan teknologi face recognition dan menerima input dari pengguna untuk menentukan preferensi buku bacaan mereka berdasarkan ekspresi emosional.